@echo off
echo 🔧 QUICK FIX: Installing all missing dependencies...
cd /d "%~dp0"

echo 📦 Installing missing packages...
npm install framer-motion@^10.16.4 @radix-ui/react-slot class-variance-authority clsx

echo 🧹 Clearing Next.js cache...
if exist .next rmdir /s /q .next

echo 🚀 Starting development server...
npm run dev
