apiVersion: apps/v1
kind: Deployment
metadata:
  name: gqcars-web
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gqcars-web
  template:
    metadata:
      labels:
        app: gqcars-web
    spec:
      containers:
      - name: web
        image: gqcars/web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5