name: Deploy to GitHub Pages (DISABLED)

# Disabled: This Next.js app uses API routes and database features
# that are not compatible with static GitHub Pages deployment.
# Use Vercel for full-stack deployment instead.

on:
  workflow_dispatch: # Only run manually
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd apps/web
        npm ci
        
    - name: Generate Prisma Client
      run: |
        cd apps/web
        npx prisma generate
        
    - name: Build Next.js application
      run: |
        cd apps/web
        npm run build
        
    - name: Export static files
      run: |
        cd apps/web
        npm run build
        mkdir -p out
        cp -r .next/static out/ || echo 'No static files to copy'
        cp -r public/* out/ || echo 'No public files to copy'
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/web/out