name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: |
        cd apps/web
        npm ci
    - name: Run tests
      run: |
        cd apps/web
        npm run test || echo 'Tests skipped - no test files found'
    - name: Run type check
      run: |
        cd apps/web
        npm run typecheck
    - name: Run lint
      run: |
        cd apps/web
        npm run lint

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Build production
      run: |
        cd apps/web
        npm run build