name: Mobile App CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/mobile/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/mobile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: apps/mobile/package-lock.json
    
    - name: Install dependencies
      working-directory: apps/mobile
      run: npm ci
    
    - name: Run linting
      working-directory: apps/mobile
      run: npm run lint
    
    - name: Run type checking
      working-directory: apps/mobile
      run: npm run typecheck
    
    - name: Run tests
      working-directory: apps/mobile
      run: npm test
    
    - name: Build Android
      working-directory: apps/mobile
      run: npm run build:android
    
    - name: Build iOS
      working-directory: apps/mobile
      run: npm run build:ios