name: Web App CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: apps/web/package-lock.json
    
    - name: Install dependencies
      working-directory: apps/web
      run: npm ci
    
    - name: Run linting
      working-directory: apps/web
      run: npm run lint
    
    - name: Run type checking
      working-directory: apps/web
      run: npm run typecheck
    
    - name: Run tests
      working-directory: apps/web
      run: npm test
    
    - name: Build
      working-directory: apps/web
      run: npm run build
    
    - name: Deploy to Vercel
      if: github.ref == 'refs/heads/main'
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npm install -g vercel
        vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        vercel build --prod --token=$VERCEL_TOKEN
        vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN